import React from 'react'
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: "Ecommerce Back-end",
    description: "Generated by create next app",
};

function StudioLayout({children}: {children:React.ReactNode}) {
  return (
    <html lang='en'>
        <body>
            {children}
        </body>
    </html>
  )
}

export default StudioLayout